name: GRASS GIS addon tests

on:
  workflow_call:
    inputs:
      NC_TEST_DATA:
        required: false
        type: string
        default: ''

jobs:
  grass-addon-tests:
    name: grass addon tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Test of GRASS GIS addon
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: addon-tests:alpine
        context: .
        file: test-docker/Dockerfile
        no-cache: true
        build-args: NC_TEST_DATA=${{ inputs.NC_TEST_DATA }}
